WebMiCay/WebMiCay/Areas/Admin/Models/IngredientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebMiCay.Models;

namespace WebMiCay.Areas.Admin.Models
{
    public class IngredientViewModel
    {
        public string MaNguyenLieu { get; set; }
        public string TenNguyenLieu { get; set; }
        public decimal GiaNguyenLieu { get; set; }
        public string DonVi { get; set; }
        public int? SoLuong { get; set; }
        public DateTime? NgayNhap { get; set; }

    }
}

WebMiCay/WebMiCay/Areas/Admin/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMiCay.Areas.Admin.Models;

namespace WebMiCay.Areas.Admin.Controllers
{
    public class IngredientController : Controller
    {
        QuanLyQuanMiCayEntities db = new QuanLyQuanMiCayEntities();
        public ActionResult Index(string searchString, string sortOrder, string genderFilter)
        {
            var data = (from nl in db.NguyenLieu
                        select new IngredientViewModel
                        {
                            MaNguyenLieu = nl.MaNguyenLieu,
                            TenNguyenLieu = nl.TenNguyenLieu,
                            GiaNguyenLieu = nl.GiaNguyenLieu,
                            DonVi = nl.DonVi,
                        });


            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                data = data.Where(b => b.TenNguyenLieu.ToLower().Contains(searchString));
            }

            if (!String.IsNullOrEmpty(genderFilter))
            {
                data = data.Where(b => b.DonVi == genderFilter);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(b => b.TenNguyenLieu);
                    break;
                default:
                    data = data.OrderBy(b => b.TenNguyenLieu);
                    break;
            }
            return View(data.ToList());
        }

        public ActionResult Addingredient()
        {
            return View();
        }

        // Action thêm mới nguyên liệu
        [HttpPost]
        public ActionResult Addingredient(string TenNguyenLieu, decimal GiaNguyenLieu, string DonVi)
        {
            try
            {
                db.Database.ExecuteSqlCommand("EXEC sp_InsertNguyenLieu @p0, @p1, @p2",
                parameters: new[]
                {
                    new SqlParameter("@p0", TenNguyenLieu),
                    new SqlParameter("@p1", GiaNguyenLieu),
                    new SqlParameter("@p2", DonVi),
                });
            }
            catch (SqlException ex)
            {
                if (ex.Number == 50000) // Kiểm tra mã lỗi của RAISERROR
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View(); // Trả về view với ViewBag đã được cập nhật
                }
                throw; // Nếu không phải lỗi từ RAISERROR, ném lại ngoại lệ
            }

            return RedirectToAction("Index");
        }

        public ActionResult Updateingredient(string tenNguyenLieu)
        {
            var model = new IngredientViewModel
            {
                TenNguyenLieu = tenNguyenLieu
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Updateingredient(string maNL, string tenNL, decimal? giaNL, string donVi)
        {
            var s = db.NguyenLieu.SingleOrDefault(c => c.MaNguyenLieu == maNL);

            if (!string.IsNullOrEmpty(tenNL))
            {
                s.TenNguyenLieu = tenNL;
            }

            if (giaNL.HasValue && giaNL.Value > 0)
            {
                s.GiaNguyenLieu = giaNL.Value;
            }

            s.DonVi = donVi;

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Deleteingredient(string maNL)
        {
            var s = db.NguyenLieu.SingleOrDefault(c => c.MaNguyenLieu == maNL);

            db.NguyenLieu.Remove(s);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}   

WebMiCay/WebMiCay/Areas/Admin/Views/Ingredient/Addingredient.cshtml
@model WebMiCay.Areas.Admin.Models.IngredientViewModel
@{
    ViewBag.Title = "Addingredient";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="canonical"
      href="https://www.wrappixel.com/templates/ample-admin-lite/" />
<link href="~/Areas/Admin/Assets/Client/css/style.min.css" rel="stylesheet" />
<body>
    <div class="page-wrapper">
        <div class="col-lg-8 col-xlg-9 col-md-12" style="margin-left:30px">
            <h3 class="hide-menu">Thêm Nguyên Liệu</h3>
            <div class="card">
                <div class="card-body">
                    <form class="form-horizontal form-material" method="post">
                        <div class="form-group mb-4">
                            <label for="example-email" class="col-md-12 p-0">Tên nguyên liệu</label>
                            <div class="col-md-12 border-bottom p-0">
                                <input type="text"
                                       placeholder="Nhập tên nguyên liệu..."
                                       class="form-control p-0 border-0"
                                       name="TenNguyenLieu" />
                                <div class="alert alert-danger hidden" style="display: none;">
                                    Không được để trống!
                                </div>
                                @if (!String.IsNullOrEmpty(ViewBag.ErrorMessage))
                                {
                                    <div class="alert alert-danger">
                                        @ViewBag.ErrorMessage
                                    </div>
                                }
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <label class="col-md-12 p-0">Giá nguyên liệu</label>
                            <div class="col-md-12 border-bottom p-0">
                                <input type="text"
                                       placeholder="VNĐ"
                                       class="form-control p-0 border-0"
                                       name="GiaNguyenLieu" />
                                <div class="alert alert-danger hidden" style="display: none;">
                                    Không được để trống!
                                </div>
                            </div>
                        </div>
                        <div class="form-group mb-4 col-xl-6">
                            <label class="col-sm-12">Đơn vị</label>
                            <div class="col-sm-12 border-bottom">
                                <select class="form-select shadow-none p-0 border-0 form-control-line " name="DonVi" id="donViSelect">
                                    <option>Lựa chọn đơn vị</option>
                                    <option>Gói</option>
                                    <option>Kg</option>
                                    <option>Cái</option>
                                </select>
                                <div class="alert alert-danger hidden" style="display: none;">
                                    Phải chọn đơn vị!
                                </div>
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <div class="col-sm-12">
                                <button class="btn btn-success">Thêm nguyên liệu</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Areas/Admin/Assets/Client/js/jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/bootstrap.bundle.min.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/app-style-switcher.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/waves.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/custom.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/sidebarmenu.js"></script>
    <script>
        (function ($) {
            "use strict";
            $(function () {
                $(".file-upload-browse").on("click", function () {
                    var file = $(this)
                        .parent()
                        .parent()
                        .parent()
                        .find(".file-upload-default");
                    file.trigger("click");
                });
                $(".file-upload-default").on("change", function () {
                    $(this)
                        .parent()
                        .find(".form-control")
                        .val(
                            $(this)
                                .val()
                                .replace(/C:\\fakepath\\/i, "")
                        );
                });
            });
        })(jQuery);
    </script>

    <button onclick="saveAndDisplayValue()">Lưu và Hiển Thị</button>

    <script>
        function saveAndDisplayValue() {
            var selectedValue = document.getElementById('donViSelect').value;
            // Lưu giá trị vào Local Storage
            localStorage.setItem('selectedValue', selectedValue);

            // Hiển thị giá trị
            displaySelectedValue();
        }

        function displaySelectedValue() {
            var selectedValue = localStorage.getItem('selectedValue');
            // Hiển thị giá trị đã chọn ở nơi khác (ví dụ: một thẻ div)
            document.getElementById('displaySelectedValue').innerText = '' + selectedValue;
        }

        // Hiển thị giá trị khi trang được tải
        displaySelectedValue();
    </script>

    <script>
        $(document).ready(function () {
            $('.btn-success').click(function (e) {
                var isValid = true;
                // Xử lý bỏ trống không nhập hay chọn gì
                $('input[type="text"]').each(function () {
                    if ($.trim($(this).val()) == '') {
                        isValid = false;
                        $(this).css({
                            "border": "1px solid red",
                            "background": "#FFCECE"
                        });
                        $(this).siblings('.alert').show();
                    }
                    else {
                        $(this).css({
                            "border": "",
                            "background": ""
                        });
                        $(this).siblings('.alert').hide();
                    }
                });

                // Xử lý không chọn đơn vị
                if ($('select[name="DonVi"]').val() == 'Lựa chọn đơn vị') {
                    isValid = false;
                    $('select[name="DonVi"]').css({
                        "border": "1px solid red",
                        "background": "#FFCECE"
                    });
                    $('select[name="DonVi"]').siblings('.alert').show();
                } else {
                    $('select[name="DonVi"]').css({
                        "border": "",
                        "background": ""
                    });
                    $('select[name="DonVi"]').siblings('.alert').hide();
                }

                if (isValid == false) {

                    e.preventDefault();
                } else {
                    alert('Cập nhật thành công!, hãy kiểm tra lại các trường thông tin xem còn có lỗi nào không trước khi thoát');
                }
            });
        });
    </script>
</body>

WebMiCay/WebMiCay/Areas/Admin/Views/Ingredient/Importingredient.cshtml
@{
    ViewBag.Title = "Importingredient";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <link rel="canonical"
          href="https://www.wrappixel.com/templates/ample-admin-lite/" />
    <link href="~/Areas/Admin/Assets/Client/css/style.min.css" rel="stylesheet" />

</head>
<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>

    <div id="main-wrapper"
         data-layout="vertical"
         data-navbarbg="skin5"
         data-sidebartype="full"
         data-sidebar-position="absolute"
         data-header-position="absolute"
         data-boxed-layout="full">
        <div class="page-wrapper">
            <div class="container-fluid">
                <!-- Row -->
                <div class="row">
                    <!-- Column -->

                    <!-- Column -->
                    <!-- Column -->
                    <div class="col-lg-8 col-xlg-9 col-md-12">
                        <h3 class="hide-menu">Bổ Sung Nguyên Liệu</h3>
                        <div class="card">
                            <div class="card-body">
                                <form class="form-horizontal form-material">
                                    <div class="form-group mb-4">
                                        <label class="col-md-12 p-0">Mã nguyên liệu</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input type="text"
                                                   placeholder="Johnathan Doe"
                                                   class="form-control p-0 border-0" />
                                        </div>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label class="col-md-12 p-0">Tên nguyên liệu</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input type="text"
                                                   placeholder="Johnathan Doe"
                                                   class="form-control p-0 border-0" />
                                        </div>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label class="col-md-12 p-0">Ngày Nhập</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input type="text"
                                                   placeholder="01/01/2024"
                                                   class="form-control p-0 border-0" />
                                        </div>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label class="col-md-12 p-0">Mã nhà cùng cấp</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input type="text"
                                                   placeholder="Johnathan Doe"
                                                   class="form-control p-0 border-0" />
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group mb-4 col-xl-6">
                                            <label class="col-md-12 p-0">Số lượng</label>
                                            <div class="col-md-12 border-bottom p-0">
                                                <input type="text"
                                                       placeholder="Johnathan Doe"
                                                       class="form-control p-0 border-0" />
                                            </div>
                                        </div>
                                        <div class="form-group mb-4 col-xl-6">
                                            <label class="col-sm-12">Đơn vị</label>
                                            <div class="col-sm-12 border-bottom">
                                                <select class="form-select shadow-none p-0 border-0 form-control-line">
                                                    <option>Gói</option>
                                                    <option>Kg</option>
                                                    <option>Cái</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mb-4">
                                        <div class="col-sm-12">
                                            <button class="btn btn-success">Update</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Areas/Admin/Assets/Client/js/jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/bootstrap.bundle.min.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/app-style-switcher.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/waves.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/custom.js"></script>
    <script src="~/Areas/Admin/Assets/Client/js/sidebarmenu.js"></script>
    <script>
        (function ($) {
            "use strict";
            $(function () {
                $(".file-upload-browse").on("click", function () {
                    var file = $(this)
                        .parent()
                        .parent()
                        .parent()
                        .find(".file-upload-default");
                    file.trigger("click");
                });
                $(".file-upload-default").on("change", function () {
                    $(this)
                        .parent()
                        .find(".form-control")
                        .val(
                            $(this)
                                .val()
                                .replace(/C:\\fakepath\\/i, "")
                        );
                });
            });
        })(jQuery);
    </script>
</body>
</html>

WebMiCay/WebMiCay/Areas/Admin/Views/Ingredient/Index.cshtml
@model List<WebMiCay.Areas.Admin.Models.IngredientViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <link href="~/Areas/Admin/Assets/dist/css/style.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Assets/dist/css/icon.css" rel="stylesheet" />
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<style>
    .dt-buttons {
        margin-right: 0;
        margin-left: 930px;
    }

    button.dt-button {
        background-color: #696cff;
        padding: 7px 20px;
        border-color: #696cff;
        box-shadow: 0 0.125rem 0.25rem 0 rgba(105,108,255,.4);
        display: inline-flex;
        align-items: center;
        justify-content: center;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        border-bottom-left-radius: 10px;
        border-bottom-right-radius: 10px;
    }
</style>
<body>
    <div class="page-wrapper">
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- basic table -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="dt-buttons">
                            <button class="dt-button">
                                <i class="bx bx-plus"></i>
                                <a href="@Url.Action("Addingredient", "Ingredient")"><span style="color:aliceblue">Thêm nguyên liệu mới</span></a>
                            </button>

                        </div>
                        <div class="card-body">
                            <!--Đây là cho phần hiển thị tìm kiếm và bộ lọc-->
                            @using (Html.BeginForm("Index", "Ingredient", FormMethod.Get, new { @class = "form-inline" }))
                            {
                                <div class="form-group">
                                    <label>Tên nguyên liệu: </label>
                                    <input type="text" class="form-control mx-sm-3"
                                           name="searchString" placeholder="Nhập tên nguyên liệu">
                                    <select name="sortOrder" class="form-control mx-sm-3">
                                        <option value="name_asc">Sắp xếp tên từ A - Z</option>
                                        <option value="name_desc">Sắp xếp tên từ Z - A</option>
                                    </select>
                                    <select name="genderFilter" class="form-control mx-sm-3">
                                        <option value="">Đơn vị</option>
                                        <option value="Kg">Kg</option>
                                        <option value="Gói">Gói</option>
                                    </select>
                                    <input type="submit" class="btn btn-danger" value="Tìm và sắp xếp">
                                </div>
                            }
                            <br />
                            <div class="table-responsive">
                                <table id="zero_config" class="table table-striped table-bordered no-wrap">
                                    <thead>
                                        <tr>
                                            <th>Mã nguyên liệu</th>
                                            <th>Tên Nguyên Liệu</th>
                                            <th>Giá</th>
                                            <th>Đơn vị</th>
                                            <th>Hành Động</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@item.MaNguyenLieu</td>
                                                <td>
                                                    <a href="javascript:void(0)" class="font-weight-medium link" name="searchString">@item.TenNguyenLieu</a>
                                                </td>
                                                <td><a href="javascript:void(0)" class="font-bold link">@item.GiaNguyenLieu</a></td>
                                                <td name="genderFilter">@item.DonVi</td>
                                                <td class="bx-tx">
                                                    <div class="d-inline-block text-nowrap">
                                                        <button class="btn btn-sm btn-icon">
                                                            <a href="@Url.Action("Updateingredient", "Ingredient", new {maNL = item.MaNguyenLieu, tenNL = item.TenNguyenLieu, giaNL= item.GiaNguyenLieu})"><i class="bx bx-edit"></i></a>
                                                        </button>
                                                        <button class="btn btn-sm btn-icon delete-record">
                                                            <a href="@Url.Action("Deleteingredient", "Ingredient", new {maNL = item.MaNguyenLieu})">
                                                                <i class="bx bx-trash"></i>
                                                            </a>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Areas/Admin/Assets/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/Areas/Admin/Assets/dist/js/app-style-switcher.js"></script>
    <script src="~/Areas/Admin/Assets/dist/js/feather.min.js"></script>
    <script src="~/Areas/Admin/Assets/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/Areas/Admin/Assets/dist/js/custom.min.js"></script>
    <style>
        .badgee {
            text-transform: uppercase;
            line-height: 0.75;
            margin-top: 15px;
            margin-left: 18px;
        }

        .badgee {
            --bs-badge-padding-x: 0.593em;
            --bs-badge-padding-y: 0.52em;
            --bs-badge-font-size: 0.8125em;
            --bs-badge-font-weight: 500;
            --bs-badge-color: #fff;
            --bs-badge-border-radius: 0.25rem;
            display: inline-block;
            padding: var(--bs-badge-padding-y) var(--bs-badge-padding-x);
            font-size: var(--bs-badge-font-size);
            font-weight: var(--bs-badge-font-weight);
            text-align: center;
            white-space: nowrap;
            vertical-align: baseline;
            border-radius: var(--bs-badge-border-radius);
        }

        .bx-sx {
            margin-right: 5px;
            background-color: #fff2d6;
            color: #ffab00;
            padding: 5px;
            border-radius: 25%;
        }

        .bx-ss {
            margin-right: 5px;
            background-color: #d7f5fc;
            color: #03c3ec;
            padding: 5px;
            border-radius: 25%;
        }

        .bx-xs {
            margin-right: 5px;
            background-color: #e7e7ff;
            color: #696cff;
            padding: 5px;
            border-radius: 25%;
        }

        a {
            color: #7c8798;
        }

        .bx-tx {
            width: 32px;
        }
    </style>
</body> 