WebMiCay/WebMiCay/Areas/Admin/Controllers/BookADController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMiCay.Models;

namespace WebMiCay.Areas.Admin.Controllers
{
    public class BookADController : Controller
    {
        QuanLyQuanMiCayEntities db = new QuanLyQuanMiCayEntities();
        public ActionResult Index(string searchString, string bookFilter)
        {
            var data = (from a in db.TaiKhoanKhach
                        join b in db.KhachHang on a.MaKH equals b.MaKH
                        join c in db.LichDat on a.MaKH equals c.MaKH
                        select new BookingViewModel
                        {
                            MaKH = b.MaKH,
                            TenKH = b.TenKH,
                            SDT = b.SDT,
                            MaTaiKhoanKhach = a.MaTaiKhoanKhach,
                            TenTaiKhoanKhach = a.TenTaiKhoanKhach,
                            MaLichDat = c.MaLichDat,
                            NgayDat = c.NgayDat,
                            GioDat = c.GioDat,
                            SoBan = c.SoBan,
                            TinhTrang = c.TinhTrang,
                            MaNV = c.MaNV
                        });

            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                data = data.Where(b => b.TenKH.ToLower().Contains(searchString));
            }

            if (!String.IsNullOrEmpty(bookFilter))
            {
                data = data.Where(c => c.TinhTrang == bookFilter);
            }

            return View(data.ToList());
        }

        public ActionResult Deletebook(string maLichDat)
        {
            var b = db.LichDat.SingleOrDefault(c => c.MaLichDat == maLichDat);

            db.LichDat.Remove(b);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

WebMiCay/WebMiCay/Areas/Admin/Views/BookAD/Index.cshtml
@model List<WebMiCay.Models.BookingViewModel>

@{
    QuanLyQuanMiCayEntities db = new QuanLyQuanMiCayEntities();
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <link href="~/Areas/Admin/Assets/dist/css/style.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Assets/dist/css/icon.css" rel="stylesheet" />
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <div class="page-wrapper">
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- basic table -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <!--Đây là cho phần hiển thị tìm kiếm và bộ lọc-->
                            @using (Html.BeginForm("Index", "BookAD", FormMethod.Get, new { @class = "form-inline" }))
                            {
                                <div class="form-group">
                                    <label>Tên khách hàng: </label>
                                    <input type="text" class="form-control mx-sm-3"
                                           name="searchString" placeholder="Nhập tên khách hàng">
                                    <select name="bookFilter" class="form-control mx-sm-3">
                                        <option value="">Tình trạng</option>
                                        <option value="Chưa duyệt">Chưa duyệt</option>
                                        <option value="Đã duyệt">Đã duyệt</option>
                                    </select>
                                    <input type="submit" class="btn btn-danger" value="Tìm và sắp xếp">
                                </div>
                            }
                            <br />
                            <div class="table-responsive">
                                <table id="zero_config" class="table table-striped table-bordered no-wrap">
                                    <thead>
                                        <tr>
                                            <th>Trạng thái</th>
                                            <th>Mã lịch đặt</th>
                                            <th>Mã tài khoản khách</th>
                                            <th>Mã khách hàng</th>
                                            <th>Tên khách hàng</th>
                                            <th>Số điện thoại</th>
                                            <th>Số bàn</th>
                                            <th>Ngày đặt</th>
                                            <th>Giờ đặt</th>
                                            <th>Nhân viên duyệt</th>
                                            <th>Hành động</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            var employee = db.NhanVien.FirstOrDefault(e => e.MaNV == item.MaNV);
                                            <tr>
                                                <td>@item.TinhTrang</td>
                                                <td>@item.MaLichDat</td>
                                                <td>@item.MaTaiKhoanKhach</td>
                                                <td>@item.MaKH</td>
                                                <td>
                                                    <a href="javascript:void(0)" class="font-weight-medium link">@item.TenKH</a>
                                                </td>
                                                <td>@item.SDT</td>
                                                <td>@item.SoBan</td>
                                                <td>@item.NgayDat</td>
                                                <td>@item.GioDat</td>
                                                <td>@(employee != null ? employee.MaNV : "N/A")</td>
                                                <td class="bx-tx">
                                                    <div class="d-inline-block text-nowrap">
                                                        <button class="btn btn-sm btn-icon delete-record" onclick="return confirm('Bạn có chắc chắn muốn xóa lịch đặt này không?');">
                                                            <a href="@Url.Action("Deletebook", "BookAD", new { maLichDat = item.MaLichDat })">
                                                                <i class="bx bx-trash"></i>
                                                            </a>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Areas/Admin/Assets/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/Areas/Admin/Assets/dist/js/app-style-switcher.js"></script>
    <script src="~/Areas/Admin/Assets/dist/js/feather.min.js"></script>
    <script src="~/Areas/Admin/Assets/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/Areas/Admin/Assets/dist/js/custom.min.js"></script>
    <style>
        .badgee {
            --bs-badge-padding-x: 0.593em;
            --bs-badge-padding-y: 0.52em;
            --bs-badge-font-size: 0.8125em;
            --bs-badge-font-weight: 500;
            --bs-badge-color: #fff;
            --bs-badge-border-radius: 0.25rem;
            display: inline-block;
            padding: var(--bs-badge-padding-y) var(--bs-badge-padding-x);
            font-size: var(--bs-badge-font-size);
            font-weight: var(--bs-badge-font-weight);
            text-align: center;
            white-space: nowrap;
            vertical-align: baseline;
            border-radius: var(--bs-badge-border-radius);
        }

        .bg-label-danger {
            background-color: #ffe0db !important;
            color: #ff3e1d !important;
        }

        .bg-label-success {
            background-color: #e8fadf !important;
            color: #71dd37 !important;
        }
    </style>
</body>